### ISSUE TITLE
Поиск книги по названию выдает неверные результаты

### ISSUE THREAD

**Issue by askrinnik** [askrinnik/MyHomeLib.NET#1]
Берем программу для работы с SQLite базой данных типа DB Browser for SQLite, открываем файл librusec_local_fb2.hlc2 и вводим запрос:
```SQL
select 
  s.SeriesTitle, 
  a.FirstName, a.LastName, 
  b.Title, b.BookID, b.UpdateDate, b.Folder, b.FileName, b.BookSize, b.IsDeleted, b.* 
from Books b
left outer join Series s on s.SeriesID = b.SeriesID
join Author_List al on al.BookID = b.BookID
join Authors a on a.AuthorID = al.AuthorID
where Title LIKE "Башня ласточки%" 
```
Получаем 3 записи с BookID: 102025, 152142, 189813
Тот же самый результат и при выполнении запроса из программы на .NET

Если же открыть программу MyHomeLib, перейти на вкладку Поиск и ввести 
LIKE "Башня ласточки%" 
Получаем 6 записей-книг. 4 из них - удаленный

Буду признателен @OleksiyPenkov  за подсказку, что я сделал не так

**Comment by OleksiyPenkov** [comment]
```
select 
  s.SeriesTitle, 
  a.FirstName, a.LastName, 
  b.Title, b.BookID, b.UpdateDate, b.Folder, b.FileName, b.BookSize, b.IsDeleted, b.* 
from Books b where b.Title LIKE "Башня ласточки%" 
```

**Comment by askrinnik** [comment]
@OleksiyPenkov , спасибо за ответ
А чем этот запрос отличается от моего?
Те же поля. И джойнов нету

**Comment by OleksiyPenkov** [comment]
А зачем нужны джойны если выборка внутри одной таблицы?

**Comment by askrinnik** [comment]
s.SeriesTitle, - это название серии
a.FirstName, a.LastName, - фамилия и имя автора
Они ж в других таблицах

Но проблема ж не в этом. Я все равно по данному запросу вижу всего три записи. Хотя из Вашей программы вижу 6 книг
Не могу понять в чем дело

**Comment by OleksiyPenkov** [comment]
Предлагаю начать с простого. Просто вывести результат из одной таблицы по названию. А потом смотреть какой из джойнов все портит.

**Comment by askrinnik** [comment]
Делал просто по одной таблице. тот же результат. всего три записи. Джойны не виноваты.
А у вас есть какой-нибудь viewer для SQLite базы? Вы не могли бы проверить?

И еще просьбочка, ткните, пожалуйста носом в строчку Вашего исходного кода, где реализован поиск. Может там у Вас какая-то предварительная обработка... Ну, типа буквы поменяны русские на английские

**Comment by askrinnik** [comment]
Разобрался с проблемой. 3 записи имеют в поле Title "Башня ласточки", а еще 3 записи "Башня Ласточки"
Причем UPPER() и LOWER() не помогают, так как функции работают только для английских букв (ASCII characters). https://www.w3resource.com/sqlite/core-functions-lower.php

Но в таблице Books есть еще поле SearchTitle, в котором название уже приведено в upper case.
Так что итоговый запрос должен быть:
```SQL
select 
  s.SeriesTitle, 
  a.FirstName, a.LastName, 
  b.Title, b.BookID, b.UpdateDate, b.Folder, b.FileName, b.BookSize, b.IsDeleted, b.* 
from Books b
left outer join Series s on s.SeriesID = b.SeriesID
join Author_List al on al.BookID = b.BookID
join Authors a on a.AuthorID = al.AuthorID
where SearchTitle LIKE "БАШНЯ ЛА%" 
```
Он возвращает 6 записей
